package kasania.entity.player;

public enum PlayerStatus {
	
	PLAYER_MEDITATION_UP,PLAYER_MEDITATION_LEFT,PLAYER_MEDTATION_DOWN,PLAYER_MEDTATION_RIGHT,
	PLAYER_PIERCE_UP,PLAYER_PIERCE_LEFT,PLAYER_PIERCE_DOWN,PLAYER_PIERCE_RIGHT,
	PLAYER_WALK_UP,PLAYER_WALK_LEFT,PLAYER_WALK_DOWN,PLAYER_WALK_RIGHT,
	PLAYER_SLASH_UP,PLAYER_SLASH_LEFT,PLAYER_SLASH_DOWN,PLAYER_SLASH_RIGHT,
	PLAYER_SHOOT_UP,PLAYER_SHOOT_LEFT,PLAYER_SHOOT_DOWN,PLAYER_SHOOT_RIGHT,
	PLAYER_DIED
}
