package kasania.resources.image;

public enum ImageName {
	MENU_GAMESTART,MENU_SETTING,MENU_GAMEEXIT,
	MENU_CURSOR,MENU_PAUSE,MENU_RESUME,MENU_EXIT,
	PLAYER_SPRITE,
	BOMB,
	TESTBACKGROUND,
	UI_INVENTORY,UI_STATUSBAR
}
